name: portfoliomanagerenv
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - conda
  - python=3.8
  - pandas
  - plotly::plotly
  - conda-forge::dash
  - conda-forge::dash-auth
  - scikit-learn
  - statsmodels
  - seaborn
  - pystan
  - conda-forge::fbprophet
  - conda-forge::dash-bootstrap-components
  - pip
  - pip:
    - yfinance
    - openpyxl